apiVersion: v1
kind: Template
metadata:
  name: provenance-checker
  annotations:
    description: This is Thoth Core - Provenance Checker
    openshift.io/display-name: 'Thoth: Provenance Checker'
    version: 0.1.0
    tags: poc,thoth,ai-stacks,provenance-checker
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This template defines resources needed to run recommendation logic of Thoth to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    app: thoth
    template: provenance-checker
    component: provenance-checker

objects:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      generateName: 'provenance-checker-'
      labels:
        app: thoth
        component: provenance-checker
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: thoth
            component: provenance-checker
        spec:
          restartPolicy: Never
          automountServiceAccountToken: false
          containers:
            - name: provenance-checker
              image: adviser
              livenessProbe:
                # Give analyzer 10 minutes to compute results, kill it if it was not able result anything.
                tcpSocket:
                  port: 80
                initialDelaySeconds: 600
                failureThreshold: 1
                periodSeconds: 10
              env:
                - name: THOTH_LOG_ADVISER
                  value: "${THOTH_LOG_ADVISER}"
                - name: THOTH_ADVISER_OUTPUT
                  value: "${THOTH_ADVISER_OUTPUT}"
                - name: THOTH_WHITELISTED_SOURCES
                  value: "${THOTH_WHITELISTED_SOURCES}"
                - name: THOTH_ADVISER_REQUIREMENTS
                  value: "${THOTH_ADVISER_REQUIREMENTS}"
                - name: THOTH_ADVISER_REQUIREMENTS_LOCKED
                  value: "${THOTH_ADVISER_REQUIREMENTS_LOCKED}"
                - name: THOTH_JANUSGRAPH_HOST
                  value: janusgraph
                - name: THOTH_JANUSGRAPH_PORT
                  value: '80'
                - name: THOTH_ADVISER_SUBCOMMAND
                  value: 'provenance'
              resources:
                limits:
                  memory: '128Mi'
                  cpu: '500m'
                requests:
                  memory: '128Mi'
                  cpu: '500m'
parameters:
  - name: THOTH_ADVISER_OUTPUT
    required: false
    description: Remote where results should be send to
  - name: THOTH_ADVISER_REQUIREMENTS
    required: false
    description: Raw stack requirements
  - name: THOTH_ADVISER_REQUIREMENTS_LOCKED
    required: false
    description: Fully pinned down stack
    displayName: Locked requirements
  - name: THOTH_LOG_ADVISER
    required: false
    description: Log adviser actions
    displayName: Log adviser actions
    value: INFO
  - name: THOTH_WHITELISTED_SOURCES
    required: false
    description: A comma separated list of whitelisted sources.
    displayName: Whitelisted sources
    value: INFO
